# Generated by Django 3.1.1 on 2020-10-15 07:47

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201015_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=catalog.models.Product.get_path, verbose_name='Изображение'),
        ),
    ]
